"""
Document generation tools — PRD §4.3 (Analytics & Document Generation Tools).

Tools:
  - generate_invoice_pdf(bill_id) → file path
  - generate_analysis_deck(target_date) → file path
"""

import os
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from pptx import Presentation
from pptx.util import Inches, Pt
from src.db.connection import get_connection
from src.tools.analytics import get_daily_close

GENERATED_DIR = "generated"


def _ensure_dir():
    if not os.path.exists(GENERATED_DIR):
        os.makedirs(GENERATED_DIR)


def generate_invoice_pdf(bill_id: str) -> dict:
    """
    Generate an A4 PDF invoice for a finalized bill using ReportLab.
    Matches Indian GST invoice standards (simplified).

    Returns:
        {file_path: "generated/INV_bill_id.pdf", url: ...}
        or {error: ...}
    """
    conn = get_connection()
    bill = conn.execute(
        "SELECT * FROM bills WHERE bill_id = ?", (bill_id,)
    ).fetchone()

    if not bill:
        return {"error": "bill_not_found"}
    if bill["status"] != "FINALIZED":
        return {"error": "bill_not_finalized"}

    lines = conn.execute(
        "SELECT bl.*, p.name FROM bill_lines bl JOIN products p ON bl.sku_id = p.sku_id "
        "WHERE bl.bill_id = ?", (bill_id,)
    ).fetchall()

    _ensure_dir()
    file_path = os.path.join(GENERATED_DIR, f"INV_{bill_id[:8]}.pdf")

    try:
        c = canvas.Canvas(file_path, pagesize=A4)
        width, height = A4

        # Header
        c.setFont("Helvetica-Bold", 16)
        c.drawString(50, height - 50, "TAX INVOICE")
        c.setFont("Helvetica", 10)
        c.drawString(50, height - 70, f"Invoice Number: {bill_id[:8].upper()}")
        c.drawString(50, height - 85, f"Date: {bill['finalized_at'][:10]}")
        if bill["customer_name"]:
            c.drawString(50, height - 100, f"Customer: {bill['customer_name']}")

        # Table Header
        y = height - 140
        c.setFont("Helvetica-Bold", 10)
        c.drawString(50, y, "Item")
        c.drawString(250, y, "HSN")
        c.drawString(300, y, "Qty")
        c.drawString(350, y, "Rate")
        c.drawString(400, y, "Taxable")
        c.drawString(460, y, "CGST")
        c.drawString(510, y, "SGST")

        # Table Rows
        y -= 20
        c.setFont("Helvetica", 9)
        for l in lines:
            c.drawString(50, y, l["name"][:30])
            c.drawString(250, y, l["hsn_code"])
            c.drawString(300, y, f"{l['qty']:.2f}")
            c.drawString(350, y, f"{l['unit_price_paise']/100:.2f}")
            c.drawString(400, y, f"{l['line_subtotal_paise']/100:.2f}")
            c.drawString(460, y, f"{l['line_cgst_paise']/100:.2f}")
            c.drawString(510, y, f"{l['line_sgst_paise']/100:.2f}")
            y -= 15
            if y < 100:
                c.showPage()
                y = height - 50
                c.setFont("Helvetica", 9)

        # Totals
        y -= 20
        c.setFont("Helvetica-Bold", 10)
        c.drawString(350, y, "Subtotal:")
        c.drawString(450, y, f"Rs. {bill['subtotal_paise']/100:.2f}")
        y -= 15
        c.drawString(350, y, "Total CGST:")
        c.drawString(450, y, f"Rs. {bill['cgst_paise']/100:.2f}")
        y -= 15
        c.drawString(350, y, "Total SGST:")
        c.drawString(450, y, f"Rs. {bill['sgst_paise']/100:.2f}")
        y -= 20
        c.setFont("Helvetica-Bold", 12)
        c.drawString(350, y, "GRAND TOTAL:")
        c.drawString(450, y, f"Rs. {bill['total_paise']/100:.2f}")

        c.save()

        return {
            "file_path": file_path,
            "message": f"Generated invoice PDF at {file_path}",
        }
    except Exception as e:
        return {"error": "pdf_generation_failed", "message": str(e)}


def generate_analysis_deck(target_date: str) -> dict:
    """
    Generate a PPTX slide deck for daily close analysis using python-pptx.

    Returns:
        {file_path: "generated/Analysis_date.pptx"}
    """
    stats = get_daily_close(target_date)
    _ensure_dir()
    file_path = os.path.join(GENERATED_DIR, f"Daily_Close_{target_date}.pptx")

    try:
        prs = Presentation()

        # Title Slide
        title_slide_layout = prs.slide_layouts[0]
        slide = prs.slides.add_slide(title_slide_layout)
        title = slide.shapes.title
        subtitle = slide.placeholders[1]
        title.text = "Kirana Daily Analysis"
        subtitle.text = f"Date: {target_date}\nGenerated by Supermarket Ops Agent"

        # Summary Slide
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        title_shape = shapes.title
        body_shape = shapes.placeholders[1]

        title_shape.text = f"Revenue Summary ({target_date})"
        tf = body_shape.text_frame
        tf.text = f"Total Revenue: Rs. {stats['revenue_paise']/100:.2f}"

        p = tf.add_paragraph()
        p.text = f"Total Bills: {stats['bill_count']}"

        p = tf.add_paragraph()
        p.text = f"Tax Collected: Rs. {stats['total_tax_paise']/100:.2f}"

        p = tf.add_paragraph()
        p.text = "Payment Modes:"
        for mode, amount in stats['mode_split'].items():
            p_mode = tf.add_paragraph()
            p_mode.text = f"  - {mode}: Rs. {amount/100:.2f}"

        # Top Items Slide
        slide2 = prs.slides.add_slide(bullet_slide_layout)
        title2 = slide2.shapes.title
        body2 = slide2.placeholders[1]
        title2.text = "Top Selling Items"
        tf2 = body2.text_frame

        if stats["top_items"]:
            for i, item in enumerate(stats["top_items"][:5]):
                if i == 0:
                    tf2.text = f"{item['name']} - Qty: {item['qty_sold']}, Rev: Rs. {item['revenue_paise']/100:.2f}"
                else:
                    p = tf2.add_paragraph()
                    p.text = f"{item['name']} - Qty: {item['qty_sold']}, Rev: Rs. {item['revenue_paise']/100:.2f}"
        else:
            tf2.text = "No sales data for this date."

        prs.save(file_path)

        return {
            "file_path": file_path,
            "message": f"Generated analysis deck at {file_path}",
        }
    except Exception as e:
        return {"error": "pptx_generation_failed", "message": str(e)}
